### ISSUE TITLE
ImportError: No modile named _mask

### ISSUE THREAD

**Issue by PGodzilla** [lichengunc/mask-faster-rcnn#2]
python tools/make_coco_minus_refer_instances.py
...
import external._mask as _mask 
ImportError: No modile named _mask

can someone tell me how to resolve it? 
thanks!!

**Comment by lichengunc** [comment]
Please go to refer/ and run "make" :-)

**Comment by zhaipeichen** [comment]
> python tools/make_coco_minus_refer_instances.py
> ...
> import external._mask as _mask
> ImportError: No modile named _mask
> 
> can someone tell me how to resolve it?
> thanks!!

我遇到了和你一样的问题。在mask-faster-rcnnn要求的PYTHON2.7下面运行不了make
